/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as MyListRouteImport } from './routes/my-list'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionsIndexRouteImport } from './routes/collections/index'
import { Route as LibrarySeriesRouteImport } from './routes/library/series'
import { Route as LibraryMoviesRouteImport } from './routes/library/movies'
import { Route as CollectionsIdRouteImport } from './routes/collections/$id'
import { Route as LibraryMoviesIndexRouteImport } from './routes/library/movies/index'
import { Route as LibraryMoviesGenreGenreRouteImport } from './routes/library/movies/genre/$genre'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const MyListRoute = MyListRouteImport.update({
  id: '/my-list',
  path: '/my-list',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrarySeriesRoute = LibrarySeriesRouteImport.update({
  id: '/library/series',
  path: '/library/series',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryMoviesRoute = LibraryMoviesRouteImport.update({
  id: '/library/movies',
  path: '/library/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIdRoute = CollectionsIdRouteImport.update({
  id: '/collections/$id',
  path: '/collections/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryMoviesIndexRoute = LibraryMoviesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LibraryMoviesRoute,
} as any)
const LibraryMoviesGenreGenreRoute = LibraryMoviesGenreGenreRouteImport.update({
  id: '/genre/$genre',
  path: '/genre/$genre',
  getParentRoute: () => LibraryMoviesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/history': typeof HistoryRoute
  '/my-list': typeof MyListRoute
  '/offline': typeof OfflineRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/library/movies': typeof LibraryMoviesRouteWithChildren
  '/library/series': typeof LibrarySeriesRoute
  '/collections/': typeof CollectionsIndexRoute
  '/library/movies/': typeof LibraryMoviesIndexRoute
  '/library/movies/genre/$genre': typeof LibraryMoviesGenreGenreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/history': typeof HistoryRoute
  '/my-list': typeof MyListRoute
  '/offline': typeof OfflineRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/library/series': typeof LibrarySeriesRoute
  '/collections': typeof CollectionsIndexRoute
  '/library/movies': typeof LibraryMoviesIndexRoute
  '/library/movies/genre/$genre': typeof LibraryMoviesGenreGenreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/history': typeof HistoryRoute
  '/my-list': typeof MyListRoute
  '/offline': typeof OfflineRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/library/movies': typeof LibraryMoviesRouteWithChildren
  '/library/series': typeof LibrarySeriesRoute
  '/collections/': typeof CollectionsIndexRoute
  '/library/movies/': typeof LibraryMoviesIndexRoute
  '/library/movies/genre/$genre': typeof LibraryMoviesGenreGenreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/history'
    | '/my-list'
    | '/offline'
    | '/settings'
    | '/setup'
    | '/collections/$id'
    | '/library/movies'
    | '/library/series'
    | '/collections/'
    | '/library/movies/'
    | '/library/movies/genre/$genre'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/history'
    | '/my-list'
    | '/offline'
    | '/settings'
    | '/setup'
    | '/collections/$id'
    | '/library/series'
    | '/collections'
    | '/library/movies'
    | '/library/movies/genre/$genre'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/history'
    | '/my-list'
    | '/offline'
    | '/settings'
    | '/setup'
    | '/collections/$id'
    | '/library/movies'
    | '/library/series'
    | '/collections/'
    | '/library/movies/'
    | '/library/movies/genre/$genre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  HistoryRoute: typeof HistoryRoute
  MyListRoute: typeof MyListRoute
  OfflineRoute: typeof OfflineRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  CollectionsIdRoute: typeof CollectionsIdRoute
  LibraryMoviesRoute: typeof LibraryMoviesRouteWithChildren
  LibrarySeriesRoute: typeof LibrarySeriesRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-list': {
      id: '/my-list'
      path: '/my-list'
      fullPath: '/my-list'
      preLoaderRoute: typeof MyListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/series': {
      id: '/library/series'
      path: '/library/series'
      fullPath: '/library/series'
      preLoaderRoute: typeof LibrarySeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/movies': {
      id: '/library/movies'
      path: '/library/movies'
      fullPath: '/library/movies'
      preLoaderRoute: typeof LibraryMoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$id': {
      id: '/collections/$id'
      path: '/collections/$id'
      fullPath: '/collections/$id'
      preLoaderRoute: typeof CollectionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/movies/': {
      id: '/library/movies/'
      path: '/'
      fullPath: '/library/movies/'
      preLoaderRoute: typeof LibraryMoviesIndexRouteImport
      parentRoute: typeof LibraryMoviesRoute
    }
    '/library/movies/genre/$genre': {
      id: '/library/movies/genre/$genre'
      path: '/genre/$genre'
      fullPath: '/library/movies/genre/$genre'
      preLoaderRoute: typeof LibraryMoviesGenreGenreRouteImport
      parentRoute: typeof LibraryMoviesRoute
    }
  }
}

interface LibraryMoviesRouteChildren {
  LibraryMoviesIndexRoute: typeof LibraryMoviesIndexRoute
  LibraryMoviesGenreGenreRoute: typeof LibraryMoviesGenreGenreRoute
}

const LibraryMoviesRouteChildren: LibraryMoviesRouteChildren = {
  LibraryMoviesIndexRoute: LibraryMoviesIndexRoute,
  LibraryMoviesGenreGenreRoute: LibraryMoviesGenreGenreRoute,
}

const LibraryMoviesRouteWithChildren = LibraryMoviesRoute._addFileChildren(
  LibraryMoviesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  HistoryRoute: HistoryRoute,
  MyListRoute: MyListRoute,
  OfflineRoute: OfflineRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  CollectionsIdRoute: CollectionsIdRoute,
  LibraryMoviesRoute: LibraryMoviesRouteWithChildren,
  LibrarySeriesRoute: LibrarySeriesRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
