/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibrarySeriesRouteImport } from './routes/library/series'
import { Route as LibraryMoviesRouteImport } from './routes/library/movies'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrarySeriesRoute = LibrarySeriesRouteImport.update({
  id: '/library/series',
  path: '/library/series',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryMoviesRoute = LibraryMoviesRouteImport.update({
  id: '/library/movies',
  path: '/library/movies',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library/movies': typeof LibraryMoviesRoute
  '/library/series': typeof LibrarySeriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/library/movies': typeof LibraryMoviesRoute
  '/library/series': typeof LibrarySeriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/library/movies': typeof LibraryMoviesRoute
  '/library/series': typeof LibrarySeriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/library/movies' | '/library/series'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/library/movies' | '/library/series'
  id: '__root__' | '/' | '/library/movies' | '/library/series'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibraryMoviesRoute: typeof LibraryMoviesRoute
  LibrarySeriesRoute: typeof LibrarySeriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/series': {
      id: '/library/series'
      path: '/library/series'
      fullPath: '/library/series'
      preLoaderRoute: typeof LibrarySeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/movies': {
      id: '/library/movies'
      path: '/library/movies'
      fullPath: '/library/movies'
      preLoaderRoute: typeof LibraryMoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibraryMoviesRoute: LibraryMoviesRoute,
  LibrarySeriesRoute: LibrarySeriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
