/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as MyListRouteImport } from './routes/my-list'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibrarySeriesRouteImport } from './routes/library/series'
import { Route as LibraryMoviesRouteImport } from './routes/library/movies'
import { Route as LibraryMoviesIndexRouteImport } from './routes/library/movies/index'
import { Route as LibraryMoviesGenreGenreRouteImport } from './routes/library/movies/genre/$genre'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const MyListRoute = MyListRouteImport.update({
  id: '/my-list',
  path: '/my-list',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrarySeriesRoute = LibrarySeriesRouteImport.update({
  id: '/library/series',
  path: '/library/series',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryMoviesRoute = LibraryMoviesRouteImport.update({
  id: '/library/movies',
  path: '/library/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryMoviesIndexRoute = LibraryMoviesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LibraryMoviesRoute,
} as any)
const LibraryMoviesGenreGenreRoute = LibraryMoviesGenreGenreRouteImport.update({
  id: '/genre/$genre',
  path: '/genre/$genre',
  getParentRoute: () => LibraryMoviesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/my-list': typeof MyListRoute
  '/setup': typeof SetupRoute
  '/library/movies': typeof LibraryMoviesRouteWithChildren
  '/library/series': typeof LibrarySeriesRoute
  '/library/movies/': typeof LibraryMoviesIndexRoute
  '/library/movies/genre/$genre': typeof LibraryMoviesGenreGenreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/my-list': typeof MyListRoute
  '/setup': typeof SetupRoute
  '/library/series': typeof LibrarySeriesRoute
  '/library/movies': typeof LibraryMoviesIndexRoute
  '/library/movies/genre/$genre': typeof LibraryMoviesGenreGenreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/my-list': typeof MyListRoute
  '/setup': typeof SetupRoute
  '/library/movies': typeof LibraryMoviesRouteWithChildren
  '/library/series': typeof LibrarySeriesRoute
  '/library/movies/': typeof LibraryMoviesIndexRoute
  '/library/movies/genre/$genre': typeof LibraryMoviesGenreGenreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/my-list'
    | '/setup'
    | '/library/movies'
    | '/library/series'
    | '/library/movies/'
    | '/library/movies/genre/$genre'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/my-list'
    | '/setup'
    | '/library/series'
    | '/library/movies'
    | '/library/movies/genre/$genre'
  id:
    | '__root__'
    | '/'
    | '/my-list'
    | '/setup'
    | '/library/movies'
    | '/library/series'
    | '/library/movies/'
    | '/library/movies/genre/$genre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MyListRoute: typeof MyListRoute
  SetupRoute: typeof SetupRoute
  LibraryMoviesRoute: typeof LibraryMoviesRouteWithChildren
  LibrarySeriesRoute: typeof LibrarySeriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-list': {
      id: '/my-list'
      path: '/my-list'
      fullPath: '/my-list'
      preLoaderRoute: typeof MyListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/series': {
      id: '/library/series'
      path: '/library/series'
      fullPath: '/library/series'
      preLoaderRoute: typeof LibrarySeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/movies': {
      id: '/library/movies'
      path: '/library/movies'
      fullPath: '/library/movies'
      preLoaderRoute: typeof LibraryMoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/movies/': {
      id: '/library/movies/'
      path: '/'
      fullPath: '/library/movies/'
      preLoaderRoute: typeof LibraryMoviesIndexRouteImport
      parentRoute: typeof LibraryMoviesRoute
    }
    '/library/movies/genre/$genre': {
      id: '/library/movies/genre/$genre'
      path: '/genre/$genre'
      fullPath: '/library/movies/genre/$genre'
      preLoaderRoute: typeof LibraryMoviesGenreGenreRouteImport
      parentRoute: typeof LibraryMoviesRoute
    }
  }
}

interface LibraryMoviesRouteChildren {
  LibraryMoviesIndexRoute: typeof LibraryMoviesIndexRoute
  LibraryMoviesGenreGenreRoute: typeof LibraryMoviesGenreGenreRoute
}

const LibraryMoviesRouteChildren: LibraryMoviesRouteChildren = {
  LibraryMoviesIndexRoute: LibraryMoviesIndexRoute,
  LibraryMoviesGenreGenreRoute: LibraryMoviesGenreGenreRoute,
}

const LibraryMoviesRouteWithChildren = LibraryMoviesRoute._addFileChildren(
  LibraryMoviesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MyListRoute: MyListRoute,
  SetupRoute: SetupRoute,
  LibraryMoviesRoute: LibraryMoviesRouteWithChildren,
  LibrarySeriesRoute: LibrarySeriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
